[workspace]
members = ["changes_fetcher", "postgres_db", "download_queuer", "downloader", "diff_log_builder", "semver_spec_serialization", "utils"]

[profile.bench]
debug = true

[profile.release]
debug = true