# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
schema = "tarball_analysis"
file = "src/schema/schema_tarball_analysis.rs"
#patch_file = "src/schema/schema_tarball_analysis.patch"
#import_types = ["diesel::sql_types::*", "crate::custom_types::sql_type_names::*"]
